apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  ports:
    - port: 8123 # 映射到ClickHouse的HTTP端口
      targetPort: 8123
    - port: 9000 # 映射到ClickHouse的客户端端口
      targetPort: 9000
  selector:
    app: clickhouse
